### ISSUE TITLE
Can we capture 2 images at the same time from 2 cameras? 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [riteshbhatia01/Moleculight-MultiCameraView#1]
Hi, 
     Can we capture 2 images from 2 cameras at the same time? 
Does your program use OpenCV? If not, then can we do this task using OpenCV as well？

My target is to open 2 cameras in the android at the same time and capture the frames using OpenCV.

**Comment by riteshbhatia01** [comment]
Hi Muhammad, 

The current program uses two surface views to display two cameras (front and back). Yes, we can capture two images simultaneously using two cameras. 

OpenCV could also be used to show the preview and capture images. I haven't checked the implementation using OpenCV so far as this demo was just to showcase two previews simultaneously.

Thanks!
